language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
#  - "nightly"  # nightly build - seems to error, but all 3.9 should error :/

before_install:
- pip install poetry

install:
- poetry install
- pip install -r requirements.txt
script:
- poetry build
- py.test  --cov-report term --cov=whitebeam/

after_success:
- bash <(curl -s https://codecov.io/bash)




