language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
#  - "nightly"  # nightly build - seems to error, but all 3.9 should error :/
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py build_ext --inplace
# command to run tests
script:
  - py.test  --cov-report term --cov=app/test/

after_success:
  - codecov